<?php

class ModelReportManualReport extends PT_Model
{
    public function addManualReport($data)
    {
//        echo "INSERT INTO " . DB_PREFIX . "dsr SET customer_id = '" . (int) $data['customer_group_id'] . "', job_no = '" . $this->db->escape($data['job_no']) . "', igm_no ='" . $this->db->escape($data['igm_no']) . "', igm_date ='" . $this->db->escape($data['igm_date']) . "', po_no ='" . $this->db->escape($data['po_no']) . "', shipper ='" . $this->db->escape($data['shipper']) . "', be_heading ='" . $this->db->escape($data['be_heading']) . "', no_of_package ='" . $this->db->escape($data['no_of_package']) . "',  net_wt ='" . $this->db->escape($data['net_wt']) . "', mode ='" . $this->db->escape($data['mode']) . "', org_eta_date ='" . $this->db->escape($data['org_eta_date']) . "', shipping_line_date ='" . $this->db->escape($data['shipping_line_date']) . "', tentative_eta_date ='" . $this->db->escape($data['tentative_eta_date']) . "', expected_date ='" . $this->db->escape($data['expected_date']) . "', invoice_no ='" . $this->db->escape($data['invoice_no']) . "', invoice_date ='" . $this->db->escape($data['invoice_date']) . "', mawb_no ='" . $this->db->escape($data['mawb_no']) . "', mawb_date ='" . $this->db->escape($data['mawb_date']) . "', be_no ='" . $this->db->escape($data['be_no']) . "', be_date ='" . $this->db->escape($data['be_date']) . "', hawb_no ='" . $this->db->escape($data['hawb_no']) . "', hawb_date ='" . $this->db->escape($data['hawb_date']) . "', airline ='" . $this->db->escape($data['airline']) . "', n_document_date ='" . $this->db->escape($data['n_document_date']) . "', org_doc_date ='" . $this->db->escape($data['org_doc_date']) . "', duty_inform_date ='" . $this->db->escape($data['duty_inform_date']) . "', duty_received_date ='" . $this->db->escape($data['duty_received_date']) . "', duty_paid_date ='" . $this->db->escape($data['duty_paid_date']) . "', total_duty ='" . $this->db->escape($data['total_duty']) . "', container_cleared_date ='" . $this->db->escape($data['container_cleared_date']) . "', detention_amt ='" . $this->db->escape($data['detention_amt']) . "', customer_remark ='" . $this->db->escape($data['customer_remark']) . "', delivery_location_remark ='" . $this->db->escape($data['delivery_location_remark']) . "', container_no ='" . $this->db->escape($data['container_no']) . "', free_period_shipping_date ='" . $this->db->escape($data['free_period_shipping_date']) . "', expected_free_dt_date ='" . $this->db->escape($data['expected_free_dt_date']) . "', expected_free_dt_remark ='" . $this->db->escape($data['expected_free_dt_remark']) . "'";exit;
//             
//       $query = $this->db->query("INSERT INTO " . DB_PREFIX . "dsr SET customer_id = '" . (int) $data['customer_id'] . "', job_no = '" . $this->db->escape($data['job_no']) . "', igm_no ='" . $this->db->escape($data['igm_no']) . "', igm_date ='" . $this->db->escape($data['igm_date']) . "', po_no ='" . $this->db->escape($data['po_no']) . "', shipper ='" . $this->db->escape($data['shipper']) . "', be_heading ='" . $this->db->escape($data['be_heading']) . "', no_of_package ='" . $this->db->escape($data['no_of_package']) . "', unit ='" . $this->db->escape($data['unit']) . "', net_wt ='" . $this->db->escape($data['net_wt']) . "', mode ='" . $this->db->escape($data['mode']) . "', org_eta_date ='" . $this->db->escape($data['org_eta_date']) . "', shipping_line_date ='" . $this->db->escape($data['shipping_line_date']) . "', tentative_eta_date ='" . $this->db->escape($data['tentative_eta_date']) . "', expected_date ='" . $this->db->escape($data['expected_date']) . "', invoice_no ='" . $this->db->escape($data['invoice_no']) . "', invoice_date ='" . $this->db->escape($data['invoice_date']) . "', mawb_no ='" . $this->db->escape($data['mawb_no']) . "', mawb_date ='" . $this->db->escape($data['mawb_date']) . "', be_no ='" . $this->db->escape($data['be_no']) . "', be_date ='" . $this->db->escape($data['be_date']) . "', hawb_no ='" . $this->db->escape($data['hawb_no']) . "', hawb_date ='" . $this->db->escape($data['hawb_date']) . "', airline ='" . $this->db->escape($data['airline']) . "', n_document_date ='" . $this->db->escape($data['n_document_date']) . "', org_doc_date ='" . $this->db->escape($data['org_doc_date']) . "', duty_inform_date ='" . $this->db->escape($data['duty_inform_date']) . "', duty_received_date ='" . $this->db->escape($data['duty_received_date']) . "', duty_paid_date ='" . $this->db->escape($data['duty_paid_date']) . "', total_duty ='" . $this->db->escape($data['total_duty']) . "', container_cleared_date ='" . $this->db->escape($data['container_cleared_date']) . "', detention_amt ='" . $this->db->escape($data['detention_amt']) . "', customer_remark ='" . $this->db->escape($data['customer_remark']) . "', delivery_location_remark ='" . $this->db->escape($data['delivery_location_remark']) . "', container_no ='" . $this->db->escape($data['container_no']) . "', free_period_shipping_date ='" . $this->db->escape($data['free_period_shipping_date']) . "', expected_free_dt_date ='" . $this->db->escape($data['expected_free_dt_date']) . "', expected_free_dt_remark ='" . $this->db->escape($data['expected_free_dt_remark']) . "'");
//        
//       echo "INSERT INTO " . DB_PREFIX . "temp_dsr SET customer_id = '" . (int) $data['customer_group_id'] . "', job_no = '" . (!empty($data['job_no']) ? $this->db->escape($data['job_no']) : '') . "', igm_no ='" . (!empty($data['igm_no']) ? $this->db->escape($data['igm_no']) : '') . "', igm_date ='" . (!empty($data['igm_date']) ? $this->db->escape($data['igm_date']) : '') . "', po_no ='" . (!empty($data['po_no']) ? $this->db->escape($data['po_no']) : '') . "', shipper ='" . (!empty($data['shipper']) ? $this->db->escape($data['shipper']) : '') . "', be_heading ='" . (!empty($data['be_heading']) ? $this->db->escape($data['be_heading']) : '') . "', no_of_package ='" . (!empty($data['no_of_package']) ? $this->db->escape($data['no_of_package']) : '') . "',  net_wt ='" . (!empty($data['net_wt']) ? $this->db->escape($data['net_wt']) : '') . "', mode ='" . (!empty($data['mode']) ? $this->db->escape($data['mode']) : '') . "', org_eta_date ='" . (!empty($data['org_eta_date']) ? $this->db->escape($data['org_eta_date']) : '') . "',"
//                    . " shipping_line_date ='" . (!empty($data['shipping_line_date']) ? $this->db->escape($data['shipping_line_date']) : '') . "', tentative_eta_date ='" . (!empty($data['tentative_eta_date']) ? $this->db->escape($data['tentative_eta_date']) : '') . "', expected_date ='" . (!empty($data['expected_date']) ? $this->db->escape($data['expected_date']) : '') . "', invoice_no ='" . (!empty($data['invoice_no']) ? $this->db->escape($data['invoice_no']) : '') . "', invoice_date ='" . (!empty($data['invoice_date']) ? $this->db->escape($data['invoice_date']) : '') . "',"
//                    . " mawb_no ='" . (!empty($data['mawb_no']) ? $this->db->escape($data['mawb_no']) : '') . "', mawb_date ='" . (!empty($data['mawb_date']) ? $this->db->escape($data['mawb_date']) : '') . "', hawb_no ='" . (!empty($data['hawb_no']) ? $this->db->escape($data['hawb_no']) : '') . "', hawb_date ='" . (!empty($data['hawb_date']) ? $this->db->escape($data['hawb_date']) : '') . "', be_no ='" . (!empty($data['be_no']) ? $this->db->escape($data['be_no']) : '') . "', be_date ='" . (!empty($data['be_date']) ? $this->db->escape($data['be_date']) : '') . "',"
//                    . " airline ='" . (!empty($data['airline']) ? $this->db->escape($data['airline']) : '') . "', n_document_date ='" . (!empty($data['n_document_date']) ? $this->db->escape($data['n_document_date']) : '') . "', org_doc_date ='" . (!empty($data['org_doc_date']) ? $this->db->escape($data['org_doc_date']) : '') . "', duty_inform_date ='" . (!empty($data['duty_inform_date']) ? $this->db->escape($data['duty_inform_date']) : '') . "', duty_received_date ='" . (!empty($data['duty_received_date']) ? $this->db->escape($data['duty_received_date']) : '') . "', duty_paid_date ='" . (!empty($data['duty_paid_date']) ? $this->db->escape($data['duty_paid_date']) : '') . "',"
//                    . " total_duty ='" . (!empty($data['total_duty']) ? $this->db->escape($data['total_duty']) : '') . "', container_cleared_date ='" . (!empty($data['container_cleared_date']) ? $this->db->escape($data['container_cleared_date']) : '') . "', detention_amt ='" . (!empty($data['detention_amt']) ? $this->db->escape($data['detention_amt']) : '') . "', customer_remark ='" .(!empty($data['customer_remark']) ? $this->db->escape($data['customer_remark']) : '') . "', delivery_location_remark ='" . (!empty($data['delivery_location_remark']) ? $this->db->escape($data['delivery_location_remark']) : '') . "', "
//                    . "container_no ='" . (!empty($data['container_no']) ? $this->db->escape($data['container_no']) : '') . "', free_period_shipping_date ='" . (!empty($data['free_period_shipping_date']) ? $this->db->escape($data['free_period_shipping_date']) : '') . "', expected_free_dt_date ='" . (!empty($data['expected_free_dt_date']) ? $this->db->escape($data['expected_free_dt_date']) : '') . "', expected_free_dt_remark ='" . (!empty($data['expected_free_dt_remark']) ? $this->db->escape($data['expected_free_dt_remark']) : '') . "'";exit;
//        
        $query = $this->db->query("INSERT INTO " . DB_PREFIX . "dsr SET customer_id = '" . (int) $data['customer_group_id'] . "', job_no = '" . (!empty($data['job_no']) ? $this->db->escape($data['job_no']) : '') . "', igm_no ='" . (!empty($data['igm_no']) ? $this->db->escape($data['igm_no']) : '') . "', igm_date ='" . (!empty($data['igm_date']) ? $this->db->escape($data['igm_date']) : '') . "', po_no ='" . (!empty($data['po_no']) ? $this->db->escape($data['po_no']) : '') . "', shipper ='" . (!empty($data['shipper']) ? $this->db->escape($data['shipper']) : '') . "', be_heading ='" . (!empty($data['be_heading']) ? $this->db->escape($data['be_heading']) : '') . "', no_of_package ='" . (!empty($data['no_of_package']) ? $this->db->escape($data['no_of_package']) : '') . "',  net_wt ='" . (!empty($data['net_wt']) ? $this->db->escape($data['net_wt']) : '') . "', mode ='" . (!empty($data['mode']) ? $this->db->escape($data['mode']) : '') . "', org_eta_date ='" . (!empty($data['org_eta_date']) ? $this->db->escape($data['org_eta_date']) : '') . "',"
                    . " shipping_line_date ='" . (!empty($data['shipping_line_date']) ? $this->db->escape($data['shipping_line_date']) : '') . "', tentative_eta_date ='" . (!empty($data['tentative_eta_date']) ? $this->db->escape($data['tentative_eta_date']) : '') . "', expected_date ='" . (!empty($data['expected_date']) ? $this->db->escape($data['expected_date']) : '') . "', invoice_no ='" . (!empty($data['invoice_no']) ? $this->db->escape($data['invoice_no']) : '') . "', invoice_date ='" . (!empty($data['invoice_date']) ? $this->db->escape($data['invoice_date']) : '') . "',"
                    . " mawb_no ='" . (!empty($data['mawb_no']) ? $this->db->escape($data['mawb_no']) : '') . "', mawb_date ='" . (!empty($data['mawb_date']) ? $this->db->escape($data['mawb_date']) : '') . "', hawb_no ='" . (!empty($data['hawb_no']) ? $this->db->escape($data['hawb_no']) : '') . "', hawb_date ='" . (!empty($data['hawb_date']) ? $this->db->escape($data['hawb_date']) : '') . "', be_no ='" . (!empty($data['be_no']) ? $this->db->escape($data['be_no']) : '') . "', be_date ='" . (!empty($data['be_date']) ? $this->db->escape($data['be_date']) : '') . "',"
                    . " airline ='" . (!empty($data['airline']) ? $this->db->escape($data['airline']) : '') . "', n_document_date ='" . (!empty($data['n_document_date']) ? $this->db->escape($data['n_document_date']) : '') . "', org_doc_date ='" . (!empty($data['org_doc_date']) ? $this->db->escape($data['org_doc_date']) : '') . "', duty_inform_date ='" . (!empty($data['duty_inform_date']) ? $this->db->escape($data['duty_inform_date']) : '') . "', duty_received_date ='" . (!empty($data['duty_received_date']) ? $this->db->escape($data['duty_received_date']) : '') . "', duty_paid_date ='" . (!empty($data['duty_paid_date']) ? $this->db->escape($data['duty_paid_date']) : '') . "',"
                    . " total_duty ='" . (!empty($data['total_duty']) ? $this->db->escape($data['total_duty']) : '') . "', container_cleared_date ='" . (!empty($data['container_cleared_date']) ? $this->db->escape($data['container_cleared_date']) : '') . "', detention_amt ='" . (!empty($data['detention_amt']) ? $this->db->escape($data['detention_amt']) : '') . "', customer_remark ='" .(!empty($data['customer_remark']) ? $this->db->escape($data['customer_remark']) : '') . "', delivery_location_remark ='" . (!empty($data['delivery_location_remark']) ? $this->db->escape($data['delivery_location_remark']) : '') . "', "
                    . "container_no ='" . (!empty($data['container_no']) ? $this->db->escape($data['container_no']) : '') . "', free_period_shipping_date ='" . (!empty($data['free_period_shipping_date']) ? $this->db->escape($data['free_period_shipping_date']) : '') . "', expected_free_dt_date ='" . (!empty($data['expected_free_dt_date']) ? $this->db->escape($data['expected_free_dt_date']) : '') . "', expected_free_dt_remark ='" . (!empty($data['expected_free_dt_remark']) ? $this->db->escape($data['expected_free_dt_remark']) : '') . "'");
       
        return $query;
    }

    public function editManualReport($customer_id, $data)
    {
        $customer_name = $this->db->query("SELECT DISTINCT * FROM " . DB_PREFIX . "customer_group WHERE customer_group_id = '" . (int)$data['customer_group_id'] . "'");

        $this->db->query("UPDATE " . DB_PREFIX . "customer SET  customer_group_id = '" . (int)$data['customer_group_id'] . "',name = '" . $this->db->escape((string)$customer_name->row['short_form']) . "',area_id = '" . (int)$data['Area'] . "',mobile = '" . $this->db->escape((string)$data['mobile']) . "',email = '" . $this->db->escape((string)$data['email']) . "', password = '" . $this->db->escape(password_hash(html_entity_decode($data['password'], ENT_QUOTES, 'UTF-8'), PASSWORD_DEFAULT)) . "',status = '" . (isset($data['status']) ? (int)$data['status'] : 0) . "', date_modified = NOW(), date_added = NOW() WHERE customer_id = '" . (int)$customer_id . "'");

    }

    public function deleteManualReport($customer_id)
    {
        $this->db->query("DELETE FROM " . DB_PREFIX . "customer WHERE customer_id = '" . (int)$customer_id . "'");

        $this->cache->delete('customer');
    }

    public function getManualReport($customer_id)
    {
        $query = $this->db->query("SELECT DISTINCT * FROM " . DB_PREFIX . "customer WHERE customer_id = '" . (int)$customer_id . "'");

        return $query->row;
    }
    public function getManualReports()
    {
        $query = $this->db->query("SELECT DISTINCT * FROM " . DB_PREFIX . "customer WHERE status = '1'");

        return $query->rows;
    }
}
